spring:
  application:
    name: streaming-settlement
  profiles:
    active: local

  datasource:
    primary:
      jdbc-url: ${PRIMARY_DB_URL}
      username: ${PRIMARY_DB_USERNAME}
      password: ${PRIMARY_DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    replica:
      jdbc-url: ${REPLICA_DB_URL}
      username: ${REPLICA_DB_USERNAME}
      password: ${REPLICA_DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            redirect-uri: ${SERVER_DOMAIN}/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

jwt:
  secret: ${JWT_SECRET_KEY}

server:
  port: ${SERVER_PORT}

frontend:
  base-url: ${FRONTEND_BASE_URL:}

settlement:
  timezone: 'Asia/Seoul'